#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x9B8AA8CA2C77FFB0 (dlitz@dlitz.net)
#
Name     : pycrypto
Version  : 2.6.1
Release  : 52
URL      : https://pypi.debian.net/pycrypto/pycrypto-2.6.1.tar.gz
Source0  : https://pypi.debian.net/pycrypto/pycrypto-2.6.1.tar.gz
Source1  : https://pypi.debian.net/pycrypto/pycrypto-2.6.1.tar.gz.asc
Summary  : Cryptographic modules for Python.
Group    : Development/Tools
License  : Python-2.0
Requires: pycrypto-license = %{version}-%{release}
Requires: pycrypto-python = %{version}-%{release}
Requires: pycrypto-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : gmp-dev
BuildRequires : python3-dev
Patch1: cve-2013-7459.patch
Patch2: CVE-2018-6594.patch

%description
Python Cryptography Toolkit (pycrypto)
======================================
This is a collection of both secure hash functions (such as SHA256 and
RIPEMD160), and various encryption algorithms (AES, DES, RSA, ElGamal,
etc.).  The package is structured to make adding new modules easy.
This section is essentially complete, and the software interface will
almost certainly not change in an incompatible way in the future; all
that remains to be done is to fix any bugs that show up.  If you
encounter a bug, please report it in the Launchpad bug tracker at

%package license
Summary: license components for the pycrypto package.
Group: Default

%description license
license components for the pycrypto package.


%package python
Summary: python components for the pycrypto package.
Group: Default
Requires: pycrypto-python3 = %{version}-%{release}

%description python
python components for the pycrypto package.


%package python3
Summary: python3 components for the pycrypto package.
Group: Default
Requires: python3-core
Provides: pypi(pycrypto)

%description python3
python3 components for the pycrypto package.


%prep
%setup -q -n pycrypto-2.6.1
cd %{_builddir}/pycrypto-2.6.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583205591
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export FCFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export FFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pycrypto
cp %{_builddir}/pycrypto-2.6.1/COPYRIGHT %{buildroot}/usr/share/package-licenses/pycrypto/d86fb3f981d36e1f2890c7aaea6f8bcbb7ad4a27
cp %{_builddir}/pycrypto-2.6.1/LEGAL/copy/LICENSE.python-2.2 %{buildroot}/usr/share/package-licenses/pycrypto/e2e326a9a73b4a86d3aa275bb1b9797ab1f047b7
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pycrypto/d86fb3f981d36e1f2890c7aaea6f8bcbb7ad4a27
/usr/share/package-licenses/pycrypto/e2e326a9a73b4a86d3aa275bb1b9797ab1f047b7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
